#!/bin/sh
set -e

echo "📦 Installing Composer dependencies..."
docker exec -t rp_php composer install --no-interaction --optimize-autoloader

echo "🗄️ Running migrations and seeding..."
docker exec -t rp_php php artisan migrate --force --seed

echo "🔒 Setting permissions..."
docker exec -t rp_php chmod -R 777 database
docker exec -t rp_php chmod -R 777 storage
docker exec -t rp_php chmod -R 777 bootstrap/cache

echo "Finished"